name: publish-helm-chart
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser to package and release Helm charts
        id: cr
        uses: helm/chart-releaser-action@v1.7.0
        with:
          version: v1.8.1
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # The token requires contents:write on the remote repository in order to
      # trigger a repository dispatch.
      - name: Trigger index update in helm-charts repository
        run: |
          curl \
            -X POST \
            --fail \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.HELM_CHARTS_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/helm-charts/dispatches \
            -d '{
              "event_type": "charts-updated",
              "client_payload": {
                "repository": "${{ github.repository }}",
                "changed_charts": "${{ steps.cr.changed_charts }}"
              }
            }'
